# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [3]:
import pandas as pd

# Notebook Presentation

In [4]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [5]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [6]:
df_apps.shape

(10841, 12)

In [7]:
df_apps.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
10121,POF Free Dating App,SOCIAL,4.20,1175188,5.30,"50,000,000",Free,0,Mature 17+,Social,"July 31, 2018",Varies with device
10118,Zello PTT Walkie Talkie,SOCIAL,4.40,695613,5.30,"50,000,000",Free,0,Everyone,Social,"August 2, 2018",Varies with device
8790,"Talkatone: Free Texts, Calls & Phone Number",COMMUNICATION,4.10,132015,25.00,"10,000,000",Free,0,Everyone,Communication,"July 18, 2018",4.2 and up
3389,Acupuncture Assistant,MEDICAL,4.50,492,39.00,"10,000",Paid,$7.99,Everyone,Medical,"April 13, 2018",4.1 and up
10324,"CM Launcher 3D - Theme, Wallpapers, Efficient",PERSONALIZATION,4.60,6700847,17.00,"100,000,000",Free,0,Teen,Personalization,"August 3, 2018",4.0.3 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [8]:
df_apps.drop(["Last_Updated", "Android_Ver"], axis=1, inplace=True)

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [9]:
df_apps_clean = df_apps.dropna()

In [10]:
df_apps_clean.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
3492,Journal Club: Medicine,MEDICAL,4.80,216,11.00,"10,000",Paid,$6.99,Everyone,Medical
728,Truck Driving Test Class 3 BC,FAMILY,1.00,1,2.00,50,Paid,$1.49,Everyone,Education
3470,ZUL - Rotativo Digital BH,AUTO_AND_VEHICLES,4.20,29,9.00,"10,000",Free,0,Everyone,Auto & Vehicles
10536,VLC for Android,VIDEO_PLAYERS,4.40,1032076,4.65,"100,000,000",Free,0,Everyone,Video Players & Editors
5440,Cestovn√© poriadky CP,MAPS_AND_NAVIGATION,4.60,2681,6.30,"100,000",Free,0,Everyone,Maps & Navigation

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [11]:
df_apps_clean = df_apps_clean.drop_duplicates(subset=["App", "Type", "Price"])

In [12]:
df_apps_clean.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
6782,Upgrade for Android DU Master,TOOLS,3.60,12993,5.20,"1,000,000",Free,0,Everyone,Tools
5400,Bing Ads,BUSINESS,4.10,1828,13.00,"100,000",Free,0,Everyone,Business
5578,‡¶¨‡¶æ‡¶Ç‡¶≤‡¶æflix,FAMILY,4.20,1111,7.30,"100,000",Free,0,Everyone,Entertainment
8647,HAWK ‚Äì Force of an Arcade Shooter. Shoot 'em up,GAME,4.60,190274,46.00,"5,000,000",Free,0,Everyone,Arcade
7874,Voxel - 3D Color by Number & Pixel Coloring Book,GAME,4.70,62561,53.00,"1,000,000",Free,0,Everyone,Board

In [13]:
df_apps_clean.shape

(8199, 10)

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [14]:
df_apps_clean.sort_values("Rating", ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
1230,Sway Medical,MEDICAL,5.00,3,22.00,100,Free,0,Everyone,Medical
1227,AJ Men's Grooming,LIFESTYLE,5.00,2,22.00,100,Free,0,Everyone,Lifestyle
1224,FK Dedinje BGD,SPORTS,5.00,36,2.60,100,Free,0,Everyone,Sports
1223,CB VIDEO VISION,PHOTOGRAPHY,5.00,13,2.60,100,Free,0,Everyone,Photography
...,...,...,...,...,...,...,...,...,...,...
1314,CR Magazine,BUSINESS,1.00,1,7.80,100,Free,0,Everyone,Business
1932,FE Mechanical Engineering Prep,FAMILY,1.00,2,21.00,"1,000",Free,0,Everyone,Education
357,Speech Therapy: F,FAMILY,1.00,1,16.00,10,Paid,$2.99,Everyone,Education
818,Familial Hypercholesterolaemia Handbook,MEDICAL,1.00,2,33.00,100,Free,0,Everyone,Medical
1208,Thistletown CI,PRODUCTIVITY,1.00,1,6.60,100,Free,0,Everyone,Productivity

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [15]:
df_apps_clean.sort_values("Size_MBs", ascending=False).head(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
9942,Talking Babsy Baby: Baby Games,LIFESTYLE,4.00,140995,100.00,"10,000,000",Free,0,Everyone,Lifestyle;Pretend Play
10687,Hungry Shark Evolution,GAME,4.50,6074334,100.00,"100,000,000",Free,0,Teen,Arcade
9943,Miami crime simulator,GAME,4.00,254518,100.00,"10,000,000",Free,0,Mature 17+,Action
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation
3144,Vi Trainer,HEALTH_AND_FITNESS,3.60,124,100.00,"5,000",Free,0,Everyone,Health & Fitness

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [16]:
df_apps_clean.sort_values("Reviews", ascending=False).head(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger ‚Äì Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [17]:
ratings = df_apps_clean["Content_Rating"].value_counts()

In [18]:
import plotly.express as px

In [33]:
fig = px.pie(labels=ratings.index, title="Content Ratings", names=ratings.index, values=ratings.values, hole=0.25)

In [34]:
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [47]:
df_apps_clean["Installs"] = pd.to_numeric(df_apps_clean["Installs"].str.replace(",", ""))

In [48]:
df_apps_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   int64
 6   Type            8199 non-null   object
 7   Price           8199 non-null   object
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 704.6+ KB

In [57]:
df = df_apps_clean["Installs"].value_counts().reset_index().sort_values("index", ascending=False)
df.columns = ["Tier", "Installs"]

In [60]:
df_installs = df
df_installs

          Tier  Installs
16  1000000000        20
15   500000000        24
12   100000000       189
10    50000000       202
3     10000000       933
5      5000000       607
0      1000000      1417
6       500000       504
1       100000      1096
7        50000       457
2        10000       988
8         5000       425
4         1000       698
11         500       199
9          100       303
14          50        56
13          10        69
17           5         9
18           1         3

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

### The most expensive apps sub $250

### Highest Grossing Paid Apps (ballpark estimate)

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

### Vertical Bar Chart - Highest Competition (Number of Apps)

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

# Grouped Bar Charts: Free vs. Paid Apps per Category

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.